services:
  backend:
    build: ./backend
    environment:
      - FLASK_ENV=${FLASK_ENV}

  frontend:
    platform: "linux/amd64"
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend
